from . import appointments
from . import patient
from . import doctor
from . import hospital
from . import specialization
from . import prescription
from . import prescription_line
from . import res_partner
from . import sale_order
from . import stock_picking